### PR TITLE
Support Immutable 4

### PR DESCRIPTION
**Pull request by Aghassi**
Updates to use Collection and isCollection per the release notes.

Adds a lockfile and adjusts the package.json to point to ^4.0.0 for immutable

Full release notes https://github.com/immutable-js/immutable-js/releases/tag/v4.0.0

All tests pass.

### CODE REVIEW

**Comment by Aghassi** [comment]
@Skn0tt This PR is ready for review. Please let me know if you see any problems with it. Seems you may be the only contributor left on this repo so don't want this to go unseen 😄

**Review by Skn0tt — APPROVED** [review]
PR seems fine to me. I don't have write access, however. If maintenance has stopped, maybe you can open a fork?

**Comment by Aghassi** [comment]
@Skn0tt thanks! Hopefully @actra-gschuster can do a merge and release? Otherwise, I will fork and republish. Appreciate the review!

**Comment by vokeit-gschuster** [comment]
Thanks for the PR.
I'm busy atm but will try to have a look at it within the next week and will prepare a release then.

**Comment by Aghassi** [comment]
Thanks for merging @vokeit-gschuster! Let me know when the NPM publish happens :)

**Pull request merged**
